/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 4fefb68c7c86acc90866086e192c8957)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat" | "ReportAgent";
	}
	interface Env {
		BREVO_SENDER_EMAIL: "noreply@ivonka-roman-forever.love";
		BREVO_SENDER_NAME: "Wedding RSVP Bot";
		OPENAI_API_KEY: string;
		SECRET: string;
		SECRET_REPORT_TOKEN: string;
		COUPLE_SECRET: string;
		FIREWORKS_API_KEY: string;
		BREVO_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		R2_ACCESS_KEY_ID: string;
		R2_SECRET_ACCESS_KEY: string;
		R2_ENDPOINT: string;
		Chat: DurableObjectNamespace /* Chat */;
		ReportAgent: DurableObjectNamespace /* ReportAgent */;
		BUCKET: R2Bucket;
		DB: D1Database;
		AI: Ai;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BREVO_SENDER_EMAIL" | "BREVO_SENDER_NAME" | "OPENAI_API_KEY" | "SECRET" | "SECRET_REPORT_TOKEN" | "COUPLE_SECRET" | "FIREWORKS_API_KEY" | "BREVO_API_KEY" | "ANTHROPIC_API_KEY" | "R2_ACCESS_KEY_ID" | "R2_SECRET_ACCESS_KEY" | "R2_ENDPOINT">> {}
}
